version: 1
profile: cloud.production

install:
  layout: binary-package

expose:
  - domain: deploy.sdkwork.com
    tls: sdkwork.com
    mode: api

  - domain: deploy-app.sdkwork.com
    tls: sdkwork.com
    mode: api

  - domain: deploy-admin.sdkwork.com
    tls: sdkwork.com
    mode: api

packages: []

overrides: {}
